/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CoffeeModal: typeof import('./components/CoffeeModal.vue')['default']
    DebugModal: typeof import('./components/DebugModal.vue')['default']
    DesktopList: typeof import('./components/DesktopList.vue')['default']
    Galleria: typeof import('primevue/galleria')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginModal: typeof import('./components/LoginModal.vue')['default']
    MapMarker: typeof import('./components/MapMarker.vue')['default']
    MobileList: typeof import('./components/MobileList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheMap: typeof import('./components/TheMap.vue')['default']
  }
}
