/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AvatarStack: typeof import('./components/AvatarStack.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    CoffeeCard: typeof import('./components/CoffeeCard.vue')['default']
    DebugModal: typeof import('./components/DebugModal.vue')['default']
    DesktopHeader: typeof import('./components/DesktopHeader.vue')['default']
    DesktopList: typeof import('./components/DesktopList.vue')['default']
    DesktopSidebar: typeof import('./components/DesktopSidebar.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FilterModal: typeof import('./components/FilterModal.vue')['default']
    Galleria: typeof import('primevue/galleria')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    JoinEventModal: typeof import('./components/JoinEventModal.vue')['default']
    LandingCTA: typeof import('./components/LandingCTA.vue')['default']
    LandingFooter: typeof import('./components/LandingFooter.vue')['default']
    LandingHeader: typeof import('./components/LandingHeader.vue')['default']
    LoginModal: typeof import('./components/LoginModal.vue')['default']
    MobileFooter: typeof import('./components/MobileFooter.vue')['default']
    MobileHeader: typeof import('./components/MobileHeader.vue')['default']
    MobileList: typeof import('./components/MobileList.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    SlidingWord: typeof import('./components/SlidingWord.vue')['default']
    TagList: typeof import('./components/TagList.vue')['default']
    TagsIcon: typeof import('./components/TagsIcon.vue')['default']
    TheMap: typeof import('./components/TheMap.vue')['default']
    ThreeDotsSpinner: typeof import('./components/svg/ThreeDotsSpinner.vue')['default']
  }
}
